### ISSUE TITLE
sln won't open in vsstudio due to missing TestUuid7

### ISSUE THREAD

**Issue by RzNmKX** [stevesimmons/uuid7-csharp#2]
`C:\Users\Austin\source\repos\TestUuid7\TestUuid7.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\Austin\source\repos\TestUuid7\TestUuid7.csproj'.  C:\Users\Austin\source\repos\TestUuid7\TestUuid7.csproj`

(my name is Austin)

from Uuid7.sln:
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TestUuid7", "..\TestUuid7\TestUuid7.csproj", "{2060FCD2-2021-47E3-8BC9-CA0120C3CAAA}"
	ProjectSection(ProjectDependencies) = postProject
		{E97DD0BF-BD64-4B47-8F00-0E6685CCE1E8} = {E97DD0BF-BD64-4B47-8F00-0E6685CCE1E8}
	EndProjectSection
EndProject`

**Comment by stevesimmons** [comment]
Thanks Austin. I'll look at that.

**Comment by stevesimmons** [comment]
Committed a new version with both the main project and test project in the `/Src` directory.
